/*****************************************************************************\
*    Program:		bgapi2 - Baumer GenTL consumer
*    Purpose:       global definitions of common feature names
*
*    Created:		19.09.2011
*    Author:		Thomas Oelschlaeger
*    Copyright:		Baumer Optronic GmbH, Radeberg
\*****************************************************************************/

#ifndef _BGAPI2_FEATURENAMES_H__
#define _BGAPI2_FEATURENAMES_H__

#define SFNCVERSION 1.5


#define SFNC_DEVICECONTROL "DeviceControl"
#define SFNC_DEVICE_VENDORNAME "DeviceVendorName"
#define SFNC_DEVICE_MODELNAME "DeviceModelName"
#define SFNC_DEVICE_MANUFACTURERINFO "DeviceManufacturerInfo"
#define SFNC_DEVICE_VERSION "DeviceVersion"
#define SFNC_DEVICE_FIRMWAREVERSION "DeviceFirmwareVersion"
#define SFNC_DEVICE_SFNCVERSIONMAJOR "DeviceSFNCVersionMajor"
#define SFNC_DEVICE_SFNCVERSIONMINOR "DeviceSFNCVersionMinor"
#define SFNC_DEVICE_SFNCVERSIONSUBMINOR "DeviceSFNCVersionSubMinor"
#define SFNC_DEVICE_MANIFESTENTRYSELECTOR "DeviceManifestEntrySelector"
#define SFNC_DEVICE_MANIFESTXMLMAJORVERSION "DeviceManifestXMLMajorVersion"
#define SFNC_DEVICE_MANIFESTXMLMINORVERSION "DeviceManifestXMLMinorVersion"
#define SFNC_DEVICE_MANIFESTXMLSUBMINORVERSION "DeviceManifestXMLSubMinorVersion"
#define SFNC_DEVICE_MANIFESTSCHEMAMAJORVERSION "DeviceManifestSchemaMajorVersion"
#define SFNC_DEVICE_MANIFESTSCHEMAMINORVERSION "DeviceManifestSchemaMinorVersion"
#define SFNC_DEVICE_MANIFESTPRIMARYURL "DeviceManifestPrimaryURL"
#define SFNC_DEVICE_MANIFESTSECONDARYURL "DeviceManifestSecondaryURL"
#define SFNC_DEVICE_ID "DeviceID"			 //depreciated SFNC2.0, replaced with "DeviceSerialNumber"
#define SFNC_DEVICE_SERIALNUMBER  "DeviceSerialNumber"  //starting with SFNC2.0 
#define SFNC_DEVICE_USERID "DeviceUserID"
#define SFNC_DEVICE_RESET "DeviceReset"
#define SFNC_DEVICE_REGISTERSSTREAMINGSTART "DeviceRegistersStreamingStart"
#define SFNC_DEVICE_REGISTERSSTREAMINGEND "DeviceRegistersStreamingEnd"
#define SFNC_DEVICE_REGISTERSCHECK "DeviceRegistersCheck"
#define SFNC_DEVICE_REGISTERSVALID "DeviceRegistersValid"
#define SFNC_DEVICE_MAXTHROUGHPUT "DeviceMaxThroughput"
#define SFNC_DEVICE_TEMERATURESELECTOR "DeviceTemperatureSelector"
#define SFNC_DEVICE_TEMPERATURE "DeviceTemperature"
#define SFNC_DEVICE_CLOCKSELECTOR "DeviceClockSelector"
#define SFNC_DEVICE_CLOCKFREQUENCY "DeviceClockFrequency"
#define SFNC_DEVICE_SERIALPORTSELECTOR "DeviceSerialPortSelector"


#define SFNC_IMAGEFORMATCONTROL "ImageFormatControl"
#define SFNC_SENSORWIDTH "SensorWidth"
#define SFNC_SENSORHEIGHT "SensorHeight"
#define SFNC_SENSORTABS "SensorTaps"
#define SFNC_SENSORDIGITIZATIONTABS "SensorDigitizationTaps"
#define SFNC_WIDTHMAX "WidthMax"
#define SFNC_HEIGHTMAX "HeightMax"
#define SFNC_WIDTH "Width"
#define SFNC_HEIGHT "Height"
#define SFNC_OFFSETX "OffsetX"
#define SFNC_OFFSETY "OffsetY"
#define SFNC_LINEPITCH "LinePitch"
#define SFNC_BINNINGHORIZONTAL "BinningHorizontal"
#define SFNC_BINNINGVERTICAL "BinningVertical"
#define SFNC_DECIMATIONHORIZONTAL "DecimationHorizontal"
#define SFNC_DECIMATIONVERTICAL "DecimationVertical"
#define SFNC_REVERSEX "ReverseX"
#define SFNC_REVERSEY "ReverseY"
#define SFNC_PIXELFORMAT "PixelFormat"
#define SFNC_PIXELCODING "PixelCoding"
#define SFNC_PIXELSIZE "PixelSize"
#define SFNC_PIXELCOLORFILTER "PixelColorFilter"
#define SFNC_PIXELDYNAMICRANGEMIN "PixelDynamicRangeMin"
#define SFNC_PIXELDYNAMICRANGEMAX "PixelDynamicRangeMax"
#define SFNC_TESTIMAGESELECTOR "TestImageSelector"


#define SFNC_ACQUISITIONCONTROL "AcquisitionControl"
#define SFNC_ACQUISITION_MODE "AcquisitionMode"
#define SFNC_ACQUISITION_START "AcquisitionStart"
#define SFNC_ACQUISITION_STOP "AcquisitionStop"
#define SFNC_ACQUISITION_ABORT "AcquisitionAbort"
#define SFNC_ACQUISITION_ARM "AcquisitionArm"
#define SFNC_ACQUISITION_FRAMECOUNT "AcquisitionFrameCount"
#define SFNC_ACQUISITION_FRAMERATE "AcquisitionFrameRate"
#define SFNC_ACQUISITION_FRAMERATEABS "AcquisitionFrameRateAbs"
#define SFNC_ACQUISITION_FRAMERATERAW "AcquisitionFrameRateRaw"
#define SFNC_ACQUISITION_LINERATE "AcquisitionLineRate"
#define SFNC_ACQUISITION_LINERATEABS "AcquisitionLineRateAbs"
#define SFNC_ACQUISITION_LINERATERAW "AcquisitionLineRateRaw"
#define SFNC_ACQUISITION_STATUSSELECTOR "AcquisitionStatusSelector"
#define SFNC_ACQUISITION_STATUS "AcquisitionStatus"
#define SFNC_TRIGGERSELECTOR "TriggerSelector"
#define SFNC_TRIGGERMODE "TriggerMode"
#define SFNC_TRIGGERSOFTWARE "TriggerSoftware"
#define SFNC_TRIGGERSOURCE "TriggerSource"
#define SFNC_TRIGGERACTIVATION "TriggerActivation"
#define SFNC_TRIGGEROVERLAP "TriggerOverlap"
#define SFNC_TRIGGERDELAY "TriggerDelay"
#define SFNC_TRIGGERDELAYABS "TriggerDelayAbs"
#define SFNC_TRIGGERDELAYRAW "TriggerDelayRaw"
#define SFNC_TRIGGERDIVIDER "TriggerDivider"
#define SFNC_TRIGGERMULTIPLIER "TriggerMultiplier"
#define SFNC_EXPOSUREMODE "ExposureMode"
#define SFNC_EXPOSURETIME "ExposureTime"
#define SFNC_EXPOSURETIMEABS "ExposureTimeAbs"
#define SFNC_EXPOSURETIMERAW "ExposureTimeRaw"
#define SFNC_EXPOSUREAUTO "ExposureAuto"


#define SFNC_DIGITALIOCONTROL "DigitalIOControl"
#define SFNC_LINESELECTOR "LineSelector"
#define SFNC_LINEMODE "LineMode"
#define SFNC_LINEINVERTER "LineInverter"
#define SFNC_LINESTATUS "LineStatus"
#define SFNC_LINESTATUSALL "LineStatusAll"
#define SFNC_LINESOURCE "LineSource"
#define SFNC_LINEFORMAT "LineFormat"
#define SFNC_USEROUTPUTSELECTOR "UserOutputSelector"
#define SFNC_USEROUTPUTVALUE "UserOutputValue"
#define SFNC_USEROUTPUTVALUEALL "UserOutputValueAll"
#define SFNC_USEROUTPUTVALUEALLMASK "UserOutputValueAllMask"


#define SFNC_COUNTERANDTIMERCONTROL "CounterAndTimerControl"
#define SFNC_COUNTERSELECTOR "CounterSelector"
#define SFNC_COUNTEREVENTSOURCE "CounterEventSource"
#define SFNC_COUNTEREVENTACTIVATION "CounterEventActivation"
#define SFNC_COUNTERRESETSOURCE "CounterResetSource"
#define SFNC_COUNTERRESETACTIVATION "CounterResetActivation"
#define SFNC_COUNTERRESET "CounterReset"
#define SFNC_COUNTERVALUE "CounterValue"
#define SFNC_COUNTERVALUEATRESET "CounterValueAtReset"
#define SFNC_COUNTERDURATION "CounterDuration"
#define SFNC_COUNTERSTATUS "CounterStatus"
#define SFNC_COUNTERTRIGGERSOURCE "CounterTriggerSource"
#define SFNC_COUNTERTRIGGERACTIVATION "CounterTriggerActivation"
#define SFNC_TIMERSELECTOR "TimerSelector"
#define SFNC_TIMERDURATION "TimerDuration"
#define SFNC_TIMERDURATIONABS "TimerDurationAbs"
#define SFNC_TIMERDURATIONRAW "TimerDurationRaw"
#define SFNC_TIMERDELAY "TimerDelay"
#define SFNC_TIMERDELAYABS "TimerDelayAbs"
#define SFNC_TIMERDELAYRAW "TimerDelayRaw"
#define SFNC_TIMERRESET "TimerReset"
#define SFNC_TIMERVALUE "TimerValue"
#define SFNC_TIMERVALUEABS "TimerValueAbs"
#define SFNC_TIMERVALUERAW "TimerValueRaw"
#define SFNC_TIMERSTATUS "TimerStatus"
#define SFNC_TIMERTRIGGERSOURCE "TimerTriggerSource"
#define SFNC_TIMERTRIGGERACTIVATION "TimerTriggerActivation"


#define SFNC_EVENTCONTROL "EventControl"
#define SFNC_EVENTSELECTOR "EventSelector"
#define SFNC_EVENTNOTIFICATION "EventNotification"

#define SFNC_EVENT_FRAMETRIGGERDATA "EventFrameTriggerData"
#define SFNC_EVENT_FRAMETRIGGER "EventFrameTrigger"
#define SFNC_EVENT_FRAMETRIGGERTIMESTAMP "EventFrameTriggerTimestamp"
#define SFNC_EVENT_FRAMETRIGGERFRAMEID "EventFrameTriggerFrameID"

#define SFNC_EVENT_EXPOSUREENDDATA "EventExposureEndData"
#define SFNC_EVENT_EXPOSUREEND "EventExposureEnd"
#define SFNC_EVENT_EXPOSUREENDTIMESTAMP "EventExposureEndTimestamp"
#define SFNC_EVENT_EXPOSUREENDFRAMEID "EventExposureEndFrameID"

#define SFNC_EVENT_ERRORDATA "EventErrorData"
#define SFNC_EVENT_ERROR "EventError"
#define SFNC_EVENT_ERRORTIMESTAMP "EventErrorTimestamp"
#define SFNC_EVENT_ERRORFRAMEID "EventErrorFrameID"
#define SFNC_EVENT_ERRORCODE "EventErrorCode"


#define SFNC_ANALOGCONTROL "AnalogControl"
#define SFNC_GAINSELECTOR "GainSelector"
#define SFNC_GAIN "Gain"
#define SFNC_GAINRAW "GainRaw"
#define SFNC_GAINABS "GainAbs"
#define SFNC_GAINAUTO "GainAuto"
#define SFNC_GAINAUTOBALANCE "GainAutoBalance"
#define SFNC_BLACKLEVELSELECTOR "BlackLevelSelector"
#define SFNC_BLACKLEVEL "BlackLevel"
#define SFNC_BLACKLEVELRAW "BlackLevelRaw"
#define SFNC_BLACKLEVELABS "BlackLevelAbs"
#define SFNC_BLACKLEVELAUTO "BlackLevelAuto"
#define SFNC_BLACKLEVELAUTOBALANCE "BlackLevelAutoBalance"
#define SFNC_WHITECLIPSELECTOR "WhiteClipSelector"
#define SFNC_WHITECLIP "WhiteClip"
#define SFNC_WHITECLIPRAW "WhiteClipRaw"
#define SFNC_WHITECLIPABS "WhiteClipAbs"
#define SFNC_BALANCERATIOSELECTOR "BalanceRatioSelector"
#define SFNC_BALANCERATIO "BalanceRatio"
#define SFNC_BALANCERATIOABS "BalanceRatioAbs"
#define SFNC_BALANCEWHITEAUTO "BalanceWhiteAuto"
#define SFNC_GAMMA "Gamma"


#define SFNC_LUTCONTROL "LUTControl"
#define SFNC_LUTSELECTOR "LUTSelector"
#define SFNC_LUTENABLE "LUTEnable"
#define SFNC_LUTINDEX "LUTIndex"
#define SFNC_LUTVALUE "LUTValue"
#define SFNC_LUTVALUEALL "LUTValueAll"


#define SFNC_ROOT "Root"
#define SFNC_DEVICE "Device"
#define SFNC_TLPARAMSLOCKED "TLParamsLocked"


#define SFNC_TRANSPORTLAYERCONTROL "TransportLayerControl"
#define SFNC_PAYLOADSIZE "PayloadSize"
#define SFNC_GEV_VERSIONMAJOR "GevVersionMajor"
#define SFNC_GEV_VERSIONMINOR "GevVersionMinor"
#define SFNC_GEV_DEVICEMODEISBIGENDIAN "GevDeviceModeIsBigEndian"
#define SFNC_GEV_DEVICECALSS "GevDeviceClass"
#define SFNC_GEV_DEVICEMODECHARACTERSET "GevDeviceModeCharacterSet"
#define SFNC_GEV_INTERFACESELECTOR "GevInterfaceSelector"
#define SFNC_GEV_MACADDRESS "GevMACAddress"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTOR "GevSupportedOptionSelector"
#define SFNC_GEV_SUPPORTEDOPTION "GevSupportedOption"
#define SFNC_GEV_SUPPORTEDIPCONFIGURATIONLLA "GevSupportedIPConfigurationLLA"
#define SFNC_GEV_SUPPORTEDIPCONFIGURATIONDHCP "GevSupportedIPConfigurationDHCP"
#define SFNC_GEV_SUPPORTEDIPCONFIGURATIONPERSISTENTIP "GevSupportedIPConfigurationPersistentIP"
#define SFNC_GEV_CURRENTIPCONFIGURATION "GevCurrentIPConfiguration"
#define SFNC_GEV_CURRENTIPCONFIGURATIONLLA "GevCurrentIPConfigurationLLA"
#define SFNC_GEV_CURRENTIPCONFIGURATIONDHCP "GevCurrentIPConfigurationDHCP"
#define SFNC_GEV_CURRENTIPCONFIGURATIONPERSISTENTIP "GevCurrentIPConfigurationPersistentIP"
#define SFNC_GEV_CURRENTIPADDRESS "GevCurrentIPAddress"
#define SFNC_GEV_CURRENTSUBNETMASK "GevCurrentSubnetMask"
#define SFNC_GEV_CURRENTDEFAULTGATEWAY "GevCurrentDefaultGateway"
#define SFNC_GEV_IPCONFIGURATIONSTATUS "GevIPConfigurationStatus"
#define SFNC_GEV_FIRSTURL "GevFirstURL"
#define SFNC_GEV_SECONDURL "GevSecondURL"
#define SFNC_GEV_NUMBEROFINTERFACES "GevNumberOfInterfaces"
#define SFNC_GEV_PERSISTENTIPADDRESS "GevPersistentIPAddress"
#define SFNC_GEV_PERSISTENTSUBNETMASK "GevPersistentSubnetMask"
#define SFNC_GEV_PERSISTENTDEFAULTGATEWAY "GevPersistentDefaultGateway"
#define SFNC_GEV_GEVLINKSPEED "GevLinkSpeed"
#define SFNC_GEV_MESSAGECHANNELCOUNT "GevMessageChannelCount"
#define SFNC_GEV_STREAMCHANNELCOUNT "GevStreamChannelCount"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSUSERDEFINEDNAME "GevSupportedOptionalCommandsUserDefinedName"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSSERIALNUMBER "GevSupportedOptionalCommandsSerialNumber"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSEVENTDATA "GevSupportedOptionalCommandsEVENTDATA"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSEVENT "GevSupportedOptionalCommandsEVENT"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSPACKETRESEND "GevSupportedOptionalCommandsPACKETRESEND"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSWRITEMEM "GevSupportedOptionalCommandsWRITEMEM"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSCONCATENATION "GevSupportedOptionalCommandsConcatenation"
#define SFNC_GEV_HEARTBEATTIMEOUT "GevHeartbeatTimeout"
#define SFNC_GEV_TIMESTAMPTICKFREQUENCY "GevTimestampTickFrequency"
#define SFNC_GEV_TIMESTAMPCONTROLLATCH "GevTimestampControlLatch"
#define SFNC_GEV_TIMESTAMPCONTROLRESET "GevTimestampControlReset"
#define SFNC_GEV_TIMESTAMPVALUE "GevTimestampValue"
#define SFNC_GEV_DISCOVERYACKDELAY "GevDiscoveryAckDelay"
#define SFNC_GEV_GVCPEXTENDEDSTATUSCODES "GevGVCPExtendedStatusCodes"
#define SFNC_GEV_GVCPPENDINGACK "GevGVCPPendingAck"
#define SFNC_GEV_GVCPHEARTBEATDISABLE "GevGVCPHeartbeatDisable"
#define SFNC_GEV_GVCPPENDINGTIMEOUT "GevGVCPPendingTimeout"
#define SFNC_GEV_PRIMARYAPPLICATIONSWITCHOVERKEY "GevPrimaryApplicationSwitchoverKey"
#define SFNC_GEV_CCP "GevCCP"
#define SFNC_GEV_PRIMARYAPPLICATIONSOCKET "GevPrimaryApplicationSocket"
#define SFNC_GEV_PRIMARYAPPLICATIONIPADDRESS "GevPrimaryApplicationIPAddress"
#define SFNC_GEV_MCPHOSTPORT "GevMCPHostPort"
#define SFNC_GEV_MCDA "GevMCDA"
#define SFNC_GEV_MCTT "GevMCTT"
#define SFNC_GEV_MCRC "GevMCRC"
#define SFNC_GEV_MCSP "GevMCSP"
#define SFNC_GEV_STREAMCHANNELSELECTOR "GevStreamChannelSelector"
#define SFNC_GEV_SCCFGUNCONDITIONALSTREAMING "GevSCCFGUnconditionalStreaming"
#define SFNC_GEV_SCCFGEXTENDEDCHUNKDATA "GevSCCFGExtendedChunkData"
#define SFNC_GEV_SCPDIRECTION "GevSCPDirection"
#define SFNC_GEV_SCPINTERFACEINDEX "GevSCPInterfaceIndex"
#define SFNC_GEV_SCPHOSTPORT "GevSCPHostPort"
#define SFNC_GEV_SCPSFIRETESTPACKET "GevSCPSFireTestPacket"
#define SFNC_GEV_SCPSDONOTFRAGMENT "GevSCPSDoNotFragment"
#define SFNC_GEV_SCPSBIGENDIAN "GevSCPSBigEndian"
#define SFNC_GEV_SCPSPACKETSIZE "GevSCPSPacketSize"
#define SFNC_GEV_SCPD "GevSCPD"
#define SFNC_GEV_SCDA "GevSCDA"
#define SFNC_GEV_SCSP "GevSCSP"
#define SFNC_GEV_MANIFESTENTRYSELECTOR "GevManifestEntrySelector"
#define SFNC_GEV_MANIFESTXMLMAJORVERSION "GevManifestXMLMajorVersion"
#define SFNC_GEV_MANIFESTXMLMINORVERSION "GevManifestXMLMinorVersion"
#define SFNC_GEV_MANIFESTXMLSUBMINORVERSION "GevManifestXMLSubMinorVersion"
#define SFNC_GEV_MANIFESTSCHEMAMAJORVERSION "GevManifestSchemaMajorVersion"
#define SFNC_GEV_MANIFESTSCHEMAMINORVERSION "GevManifestSchemaMinorVersion"
#define SFNC_GEV_MANIFESTPRIMARYURL "GevManifestPrimaryURL"
#define SFNC_GEV_MANIFESTSECONDARYURL "GevManifestSecondaryURL"
#define SFNC_CL_CONFIGURATION "ClConfiguration"
#define SFNC_CL_TIMESLOTSCOUNT "ClTimeSlotsCount"
#define SFNC_DEVICETAPGEOMETRY "DeviceTapGeometry"


#define SFNC_USERSETCONTROL "UserSetControl"
#define SFNC_USERSETSELECTOR "UserSetSelector"
#define SFNC_USERSETLOAD "UserSetLoad"
#define SFNC_USERSETSAVE "UserSetSave"
#define SFNC_USERSETDEFAULTSELECTOR "UserSetDefaultSelector"


#define SFNC_CHUNKDATACONTROL "ChunkDataControl"
#define SFNC_CHUNKMODEACTIVE "ChunkModeActive"
#define SFNC_CHUNKSELECTOR "ChunkSelector"
#define SFNC_CHUNKENABLE "ChunkEnable"
#define SFNC_CHUNKIMAGE "ChunkImage"
#define SFNC_CHUNKOFFSETX "ChunkOffsetX"
#define SFNC_CHUNKOFFSETY "ChunkOffsetY"
#define SFNC_CHUNKWIDTH "ChunkWidth"
#define SFNC_CHUNKHEIGHT "ChunkHeight"
#define SFNC_CHUNKPIXELFORMAT "ChunkPixelFormat"
#define SFNC_CHUNKPIXELDYNAMICRANGEMIN "ChunkPixelDynamicRangeMin"
#define SFNC_CHUNKPIXELDYNAMICRANGEMAX "ChunkPixelDynamicRangeMax"
#define SFNC_CHUNKDYNAMICRANGEMIN "ChunkDynamicRangeMin"
#define SFNC_CHUNKDYNAMICRANGEMAX "ChunkDynamicRangeMax"
#define SFNC_CHUNKTIMESTAMP "ChunkTimestamp"
#define SFNC_CHUNKLINESTATUSALL "ChunkLineStatusAll"
#define SFNC_CHUNKCOUNTERSELECTOR "ChunkCounterSelector"
#define SFNC_CHUNKCOUNTERVALUE "ChunkCounterValue"
#define SFNC_CHUNKCOUNTER "ChunkCounter"
#define SFNC_CHUNKTIMERSELECTOR "ChunkTimerSelector"
#define SFNC_CHUNKTIMERVALUE "ChunkTimerValue"
#define SFNC_CHUNKTIMER "ChunkTimer"
#define SFNC_CHUNKEXPOSURETIME "ChunkExposureTime"
#define SFNC_CHUNKGAINSELECTOR "ChunkGainSelector"
#define SFNC_CHUNKGAIN "ChunkGain"
#define SFNC_CHUNKBLACKLEVELSELECTOR "ChunkBlackLevelSelector"
#define SFNC_CHUNKBLACKLEVEL "ChunkBlackLevel"
#define SFNC_CHUNKLINEPITCH "ChunkLinePitch"
#define SFNC_CHUNKFRAMEID "ChunkFrameID"


#define SFNC_FILEACCESSCONTROL "FileAccessControl"
#define SFNC_FILESELECTOR "FileSelector"
#define SFNC_FILEOPERATIONSELECTOR "FileOperationSelector"
#define SFNC_FILEOPERATIONEXECUTE "FileOperationExecute"
#define SFNC_FILEOPENMODE "FileOpenMode"
#define SFNC_FILEACCESSBUFFER "FileAccessBuffer"
#define SFNC_FILEACCESSOFFSET "FileAccessOffset"
#define SFNC_FILEACCESSLENGTH "FileAccessLength"
#define SFNC_FILEOPERATIONSTATUS "FileOperationStatus"
#define SFNC_FILEOPERATIONRESULT "FileOperationResult"
#define SFNC_FILESIZE "FileSize"


#define SFNC_COLORTRANSFORMATIONCONTROL "ColorTransformationControl"
#define SFNC_COLORTRANSFORMATIONSELECTOR "ColorTransformationSelector"
#define SFNC_COLORTRANSFORMATIONENABLE "ColorTransformationEnable"
#define SFNC_COLORTRANSFORMATIONVALUESELECTOR "ColorTransformationValueSelector"
#define SFNC_COLORTRANSFORMATIONVALUE "ColorTransformationValue"


#define SFNC_ACTIONCONTROL "ActionControl"
#define SFNC_ACTIONDEVICEKEY "ActionDeviceKey"
#define SFNC_ACTIONSELECTOR "ActionSelector"
#define SFNC_ACTIONGROUPMASK "ActionGroupMask"
#define SFNC_ACTIONGROUPKEY "ActionGroupKey"


#define GENTL_SFNC_TLPORT "TLPort"
#define GENTL_SFNC_TLVENDORNAME "TLVendorName"
#define GENTL_SFNC_TLMODELNAME "TLModelName"
#define GENTL_SFNC_TLID "TLID"
#define GENTL_SFNC_TLVERSION "TLVersion"
#define GENTL_SFNC_TLPATH "TLPath"
#define GENTL_SFNC_TLTYPE "TLType"
#define GENTL_SFNC_GENTLVERSIONMAJOR "GenTLVersionMajor"
#define GENTL_SFNC_GENTLVERSIONMINOR "GenTLVersionMinor"
#define GENTL_SFNC_GENTLINTERFACEUPDATELIST "InterfaceUpdateList"
#define GENTL_SFNC_GENTLINTERFACESELECTOR "InterfaceSelector"
#define GENTL_SFNC_GENTLINTERFACEID "InterfaceID"

#define GENTL_SFNC_GEVVERSIONMAJOR "GevVersionMajor"
#define GENTL_SFNC_GEVVERSIONMINOR "GevVersionMinor"
#define GENTL_SFNC_GEVINTERFACEMACADDRESS "GevInterfaceMACAddress"
#define GENTL_SFNC_GEVINTERFACEDEFAULTIPADDRESS "GevInterfaceDefaultIPAddress"
#define GENTL_SFNC_GEVINTERFACEDEFAULTSUBNETMASK "GevInterfaceDefaultSubnetMask"
#define GENTL_SFNC_GEVINTERFACEDEFAULTGATEWAY "GevInterfaceDefaultGateway"


#define GENTL_SFNC_INTERFACEPORT "InterfacePort"
#define GENTL_SFNC_INTERFACEID "InterfaceID"
#define GENTL_SFNC_INTERFACETYPE "InterfaceType"
#define GENTL_SFNC_DEVICEUPDATELIST "DeviceUpdateList"
#define GENTL_SFNC_DEVICESELECTOR "DeviceSelector"
#define GENTL_SFNC_DEVICEID "DeviceID"
#define GENTL_SFNC_DEVICEVENDORNAME "DeviceVendorName"
#define GENTL_SFNC_DEVICEMODELNAME "DeviceModelName"
#define GENTL_SFNC_DEVICEACCESSSTATUS "DeviceAccessStatus"

#define GENTL_SFNC_GEVINTERFACEGATEWAYSELECTOR "GevInterfaceGatewaySelector"
#define GENTL_SFNC_GEVINTERFACEGATEWAY "GevInterfaceGateway"
#define GENTL_SFNC_GEVINTERFACEMACADDRESS "GevInterfaceMACAddress"
#define GENTL_SFNC_GEVINTERFACESUBNETSELECTOR "GevInterfaceSubnetSelector"
#define GENTL_SFNC_GEVINTERFACESUBNETIPADDRESS "GevInterfaceSubnetIPAddress"
#define GENTL_SFNC_GEVINTERFACESUBNETMASK "GevInterfaceSubnetMask"

#define GENTL_SFNC_DEVICEPORT "DevicePort"
#define GENTL_SFNC_DEVICEID "DeviceID"
#define GENTL_SFNC_DEVICEVENDORNAME "DeviceVendorName"
#define GENTL_SFNC_DEVICEMODELNAME "DeviceModelName"
#define GENTL_SFNC_DEVICETYPE "DeviceType"
#define GENTL_SFNC_STREAMSELECTOR "StreamSelector"
#define GENTL_SFNC_STREAMID "StreamID"

#define GENTL_SFNC_GEVDEVICEIPADDRESS "GevDeviceIPAddress"
#define GENTL_SFNC_GEVDEVICESUBNETMASK "GevDeviceSubnetMask"
#define GENTL_SFNC_GEVDEVICEMACADDRESS "GevDeviceMACAddress"
#define GENTL_SFNC_GEVDEVICEGATEWAY "GevDeviceGateway"
#define GENTL_SFNC_DEVICEENDIANESSMECHANISM "DeviceEndianessMechanism"


#define GENTL_SFNC_STREAMPORT "StreamPort"
#define GENTL_SFNC_STREAMID "StreamID"
#define GENTL_SFNC_STREAMANNOUNCEDBUFFERCOUNT "StreamAnnouncedBufferCount"
#define GENTL_SFNC_STREAMACQUISITIONMODESELECTOR "StreamAcquisitionModeSelector"
#define GENTL_SFNC_STREAMANNOUNCEBUFFERMINIMUM "StreamAnnounceBufferMinimum"
#define GENTL_SFNC_STREAMTYPE "StreamType"


#define GENTL_SFNC_BUFFERPORT "BufferPort"
#define GENTL_SFNC_BUFFERDATA "BufferData"
#define GENTL_SFNC_BUFFERUSERDATA "BufferUserData"

#endif //_BGAPI2_FEATURENAMES_H__
